#
# ██╗  ██╗██╗   ██╗███████╗██╗  ██╗███████╗████████╗ █████╗ ███████╗███████╗██╗   ██╗████████╗██╗██╗     ███████╗
# ██║ ██╔╝██║   ██║██╔════╝██║  ██║██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔════╝██║   ██║╚══██╔══╝██║██║     ██╔════╝
# █████╔╝ ██║   ██║███████╗███████║███████╗   ██║   ███████║█████╗  █████╗  ██║   ██║   ██║   ██║██║     ███████╗
# ██╔═██╗ ██║   ██║╚════██║██╔══██║╚════██║   ██║   ██╔══██║██╔══╝  ██╔══╝  ██║   ██║   ██║   ██║██║     ╚════██║
# ██║  ██╗╚██████╔╝███████║██║  ██║███████║   ██║   ██║  ██║██║     ██║     ╚██████╔╝   ██║   ██║███████╗███████║
# ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝      ╚═════╝    ╚═╝   ╚═╝╚══════╝╚══════╝

# Plugin Created by DankOfUK with help from ChatGPT
# Discord for Support: http://discord.gg/2xYgHUfubM

#
#
# Plugin Messages
#
#

reloadConfig: "Config Reloaded"
noPermissionMessage: "No Perms"

#
#
# Toggle Options
#
#

bStatsEnabled: true #If enabled it will send stats to http://bstats.org (Tracking amount of servers using the plugin)

#
#
# Discord Bot Settings
#
#
bot:
  botToken: "" #Get from developer.discord.com (https://www.youtube.com/watch?v=ibtXXoMxaho0)
  botEnabled: false
  botActivityMessage: "Test"
  botCommandPrefix: "+"
